<?php
/**
 * Quickaddtocart 
 *
 * @category    Aydus
 * @package     Aydus_QuickAddToCart
 * @author     	Aydus Consulting <davidt@aydus.com>
 */
?>
<div id="quickaddtocart">

	<div class="page-title title-buttons">
		<h1>Quick Add To Cart</h1>
	</div>

	<form id="part_search">

		<div class="part-search">
		
			<div class="part-search-input">
				<input type="text" id="part" name="q" value="<?php echo $this->getQuery() ?>" placeholder="Search for Products Here..." class="input-text" maxlength="128" autocomplete="off" />
                <button class="button"><span><span>Search</span></span></button>
				<img src="<?php echo $this->getSkinUrl('images/aydus/quickaddtocart-progress.gif') ?>" class="progress search-progress" />
			</div>
	
			<div id="part_autocomplete"></div>		
		</div>

	</form>
	
	<div class="part-border"></div>

	<form id="part_form">
		<div class="page-title title-buttons">
			<h3>Search Results</h3>
			<div class="message"></div>
		</div>
				
		<div class="part-results">
					
			<div class="part-results-items">
				<ul class="items"></ul>
			</div>
			
			<div class="clear"></div>

		</div>
				
	</form>
	
	<div class="part-border"></div>
	
	<form id="part_cart">
		<div class="page-title title-buttons">
			<h3>Cart Summary</h3>
		</div>

		<div class="part-cart">
			<div class="part-cart-loading">
			    <span class="part-cart-progress"></span>
				<img src="<?php echo $this->getSkinUrl('images/aydus/quickaddtocart-progress.gif') ?>" class="cart-progress" />
			</div>
			<div class="part-cart-load">
                <?php echo $this->getChildHtml('checkout.cart') ?>
			</div>
		</div>
	</form>
	
</div>

<script type="application/javascript">
//<![CDATA[
    var options = {
        storeUrl : "<?php echo $this->getUrl('quickaddtocart/index') ?>",
        searchForm : "#part_search",
        addtocartForm : "#part_form",
        cartForm : "#part_cart",
        searchProgress : ".search-progress",
        cartProgress : ".part-cart-loading",
        partsearchButton : ".partsearch-button",
        checkoutButton : ".checkout-button"
    };
    quickaddtocart.init(options);
    
    //prevent form submit, start ajax search
    new Event.observe("part_search", "submit", function(e){
        e.stop();
        quickaddtocart.search();
    });

    //prevent form submit, add to cart is via ajax
    new Event.observe("part_form", "submit", function(e){
        e.stop();
    });
//]]>
</script>