<?php
/**
 * Add to cart options 
 *
 * @category    Aydus
 * @package     Aydus_QuickAddToCart
 * @author     	Aydus Consulting <davidt@aydus.com>
 */
?>
<div id="select-options">

    <div class="select-options-bg"></div>
    
    <div class="select-options-container">
    
        <a href="#" class="select-options-close">Close</a>
        <div class="select-options-form"></div>
                
    </div>
</div>

