<?php
/**
 * Add to cart options 
 *
 * @category    Aydus
 * @package     Aydus_QuickAddToCart
 * @author     	Aydus Consulting <davidt@aydus.com>
 */
?>
<div id="select-options">

    <div class="select-options-bg"></div>
    
    <div class="select-options-container">
        <div class="select-options-header">
        <h3>Select Options</h3>
        <a href="#" class="select-options-close" title="Close"></a>
        </div>
        
        <div class="select-options-form">
        </div>
                
    </div>
</div>

